
import java.io.BufferedReader;
import java.io.FileReader;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on 5 Sep, 2017, 12:22:51 AM
 */

/**
 *
 * @author paksh
 */
public class Home extends javax.swing.JFrame {

    Connection conn;
    prepareStatement pst;
    ResultSet rs;
    
    
    public Home() {
        initComponents();
        conn = DBConnect.connect();
        getUserDetails();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHome = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDepositeAmount = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblUserImage = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUN = new javax.swing.JLabel();
        lblUID = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mEmp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmEmpl = new javax.swing.JMenuItem();
        jmCustomers = new javax.swing.JMenuItem();
        jmTran = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmAbt = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlHome.setBackground(new java.awt.Color(255, 204, 0));

        btnCreate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(153, 0, 0));
        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(153, 0, 0));
        btnUpdate.setText("Update Account");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(153, 0, 0));
        btnDelete.setText("Delete Account");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnDepositeAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDepositeAmount.setForeground(new java.awt.Color(153, 0, 0));
        btnDepositeAmount.setText("Deposite Amount");
        btnDepositeAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositeAmountActionPerformed(evt);
            }
        });

        btnWithdraw.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnWithdraw.setForeground(new java.awt.Color(153, 0, 0));
        btnWithdraw.setText("Withdraw Amount");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(153, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Username:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("User ID:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(153, 0, 0));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnAddUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(153, 0, 0));
        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.jpg"))); // NOI18N

        lblUN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUN.setForeground(new java.awt.Color(153, 0, 0));

        lblUID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUID.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel1)
                                .addGap(97, 97, 97)
                                .addComponent(lblUserImage))
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDepositeAmount))
                                .addGap(77, 77, 77)
                                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete)
                                    .addComponent(btnWithdraw)
                                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlHomeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate, btnDelete, btnDepositeAmount, btnUpdate, btnWithdraw});

        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblUserImage))
                            .addComponent(jLabel1))
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlHomeLayout.createSequentialGroup()
                                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblUN, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(lblUID, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositeAmount)
                    .addComponent(btnWithdraw)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pnlHomeLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreate, btnDelete, btnDepositeAmount, btnUpdate, btnWithdraw});

        jMenuBar1.setForeground(new java.awt.Color(153, 0, 0));

        mEmp.setText("Employees");

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(153, 0, 0));
        jMenuItem1.setText("Add/Delete Employee");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mEmp.add(jMenuItem1);

        jMenuBar1.add(mEmp);

        jMenu1.setText("Reports");

        jmEmpl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmEmpl.setForeground(new java.awt.Color(153, 0, 0));
        jmEmpl.setText("Employees");
        jmEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEmplActionPerformed(evt);
            }
        });
        jMenu1.add(jmEmpl);

        jmCustomers.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmCustomers.setForeground(new java.awt.Color(153, 0, 0));
        jmCustomers.setText("Customers");
        jmCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCustomersActionPerformed(evt);
            }
        });
        jMenu1.add(jmCustomers);

        jmTran.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmTran.setForeground(new java.awt.Color(153, 0, 0));
        jmTran.setText("Transaction");
        jmTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTranActionPerformed(evt);
            }
        });
        jMenu1.add(jmTran);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jmAbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jmAbt.setForeground(new java.awt.Color(153, 0, 0));
        jmAbt.setText("About us");
        jmAbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAbtActionPerformed(evt);
            }
        });
        jMenu2.add(jmAbt);

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(153, 0, 0));
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(882, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
       setVisible(false);
       Authentication an = new Authentication();
       an.setVisible(true);
       

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
       new CreateAccount().setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        new Search().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String adm=lblUID.getText();
       
        try {
            String query="Select access_level from users where id= ?";
            PreparedStatement pst1=conn.prepareStatement(query);
            pst1.setString(1,adm);
            rs=pst1.executeQuery();

            if (rs.next() && rs.getString("access_level").equals("admin")) {
                setVisible(false);
                new DeleteSearch().setVisible(true);
            }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry,Only Manager can access this!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDepositeAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositeAmountActionPerformed
       setVisible(false);
       new Deposite().setVisible(true);
    }//GEN-LAST:event_btnDepositeAmountActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        new Withdraw().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        String adm=lblUID.getText();
       
        try {
            String query="Select access_level from users where id= ?";
            PreparedStatement pst1=conn.prepareStatement(query);
            pst1.setString(1,adm);
            rs=pst1.executeQuery();

            if (rs.next() && rs.getString("access_level").equals("admin")) {
                new Users().setVisible(true);
                setVisible(false);
            }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry,Only Manager can access this!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void jmTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTranActionPerformed
        setVisible(false);
        new Transaction().setVisible(true);
    }//GEN-LAST:event_jmTranActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jmEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEmplActionPerformed
        setVisible(false);
        new Employees().setVisible(true);
    }//GEN-LAST:event_jmEmplActionPerformed

    private void jmCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCustomersActionPerformed
        setVisible(false);
        new Customers().setVisible(true);
    }//GEN-LAST:event_jmCustomersActionPerformed

    private void jmAbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAbtActionPerformed
        setVisible(false);
        new Help().setVisible(true);
    }//GEN-LAST:event_jmAbtActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       String adm=lblUID.getText();
       
        try {
            String query="Select access_level from users where id= ?";
            PreparedStatement pst1=conn.prepareStatement(query);
            pst1.setString(1,adm);
            rs=pst1.executeQuery();

            if (rs.next() && rs.getString("access_level").equals("admin")) {              
                setVisible(false);
                new AddEmp().setVisible(true);
            }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry,Only Manager can access this!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        } 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
      
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDepositeAmount;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem jmAbt;
    private javax.swing.JMenuItem jmCustomers;
    private javax.swing.JMenuItem jmEmpl;
    private javax.swing.JMenuItem jmTran;
    private javax.swing.JLabel lblUID;
    private javax.swing.JLabel lblUN;
    private javax.swing.JLabel lblUserImage;
    private javax.swing.JMenu mEmp;
    private javax.swing.JPanel pnlHome;
    // End of variables declaration//GEN-END:variables

    private void getUserDetails() {
        try {
            
            BufferedReader br = new BufferedReader(new FileReader("data.txt"));
            String data;
            
            data = br.readLine();
            
            String details[] = data.split("/");
            lblUN.setText(details[0]);
            lblUID.setText(details[1]);
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
